/**
 * This file is auto-generated by the build script.
 * It consolidates API functions for use in the application.
 * Do not edit manually.
 */
import _schema1 from './schemas/schema1.js';
import _schema2 from './schemas/schema2.js';

export { _schema1 as schema1 };
export { _schema2 as schema2 };

export default {
    schema1: _schema1,
    schema2: _schema2,
};