/**
 * This file is auto-generated by the build script.
 * It consolidates API type declarations for use in the application.
 * Do not edit manually.
 */
import type _build from './build';
import type _combineFiles from './combineFiles';
import type _convertBytes from './convertBytes';
import type _decrypt from './decrypt';
import type _each from './each';
import type _eachAsync from './eachAsync';
import type _encrypt from './encrypt';
import type _getAllFiles from './getAllFiles';
import type _hashPassword from './hashPassword';
import type _ignoreFolder_ignoreMe from './ignoreFolder/ignoreMe';
import type _ignoreMe from './ignoreMe';
import type _isUUID from './isUUID';
import type _md5 from './md5';
import type _setLocalEnvs from './setLocalEnvs';
import type _toPennies from './toPennies';
import type _utils_buildExportsTree from './utils/buildExportsTree';
import type _utils_buildFileDataList from './utils/buildFileDataList';
import type _utils_extractJSDocComment from './utils/extractJSDocComment';
import type _utils_generateFile from './utils/generateFile';
import type _utils_generateFlatExportLines from './utils/generateFlatExportLines';
import type _utils_generateImportStatements from './utils/generateImportStatements';
import type _utils_generateNamedExports from './utils/generateNamedExports';
import type _utils_generateNamespaceCode from './utils/generateNamespaceCode';
import type _utils_generateNamespaceExportLines from './utils/generateNamespaceExportLines';
import type _utils_shouldIgnore from './utils/shouldIgnore';
import type _uuid from './uuid';
import type _validatePassword from './validatePassword';

export declare const build: typeof _build;
export declare const combineFiles: typeof _combineFiles;
export declare const convertBytes: typeof _convertBytes;
export declare const decrypt: typeof _decrypt;
export declare const each: typeof _each;
export declare const eachAsync: typeof _eachAsync;
export declare const encrypt: typeof _encrypt;
export declare const getAllFiles: typeof _getAllFiles;
export declare const hashPassword: typeof _hashPassword;
export declare const ignoreMe: typeof _ignoreMe;
export declare const isUUID: typeof _isUUID;
export declare const md5: typeof _md5;
export declare const setLocalEnvs: typeof _setLocalEnvs;
export declare const toPennies: typeof _toPennies;
export declare const uuid: typeof _uuid;
export declare const validatePassword: typeof _validatePassword;

declare const _default: {
    /**
     * Builds a file from the specified source directory and writes it to the destination file.
     *
     * @param {Object} options - The options for the build process.
     * @param {string} [options.src='./src'] - The source directory to build from.
     * @param {string} [options.dest='./index.js'] - The destination file to write the built content to.
     * @param {boolean} [options.exportRoots=true] - Whether to export root files.
     * @param {string[]} [options.ignore=[]] - An array of file patterns to ignore.
     * @param {boolean} [options.includeComments=true] - Whether to include comments in the generated file.
     * @param {boolean} [options.dts=false] - Whether to generate TypeScript declaration files.
     * @returns {Promise<boolean>} A promise that resolves to true when the build is complete.
     */
    build: typeof _build;
    combineFiles: typeof _combineFiles;
    /**
     * Converts a given number of bytes into a more readable string format with appropriate units.
     *
     * @param {number} bytes - The number of bytes to convert.
     * @param {number} [precision=2] - The number of decimal places to include in the result.
     * @returns {string} The converted bytes in a string format with appropriate units.
     */
    convertBytes: typeof _convertBytes;
    decrypt: typeof _decrypt;
    each: typeof _each;
    eachAsync: typeof _eachAsync;
    encrypt: typeof _encrypt;
    getAllFiles: typeof _getAllFiles;
    hashPassword: typeof _hashPassword;
    ignoreMe: typeof _ignoreMe;
    isUUID: typeof _isUUID;
    md5: typeof _md5;
    setLocalEnvs: typeof _setLocalEnvs;
    toPennies: typeof _toPennies;
    uuid: typeof _uuid;
    validatePassword: typeof _validatePassword;
    ignoreFolder: {
        ignoreMe: typeof _ignoreFolder_ignoreMe,
    },
    utils: {
        buildExportsTree: typeof _utils_buildExportsTree,
        buildFileDataList: typeof _utils_buildFileDataList,
        extractJSDocComment: typeof _utils_extractJSDocComment,
        generateFile: typeof _utils_generateFile,
        generateFlatExportLines: typeof _utils_generateFlatExportLines,
        generateImportStatements: typeof _utils_generateImportStatements,
        generateNamedExports: typeof _utils_generateNamedExports,
        generateNamespaceCode: typeof _utils_generateNamespaceCode,
        generateNamespaceExportLines: typeof _utils_generateNamespaceExportLines,
        shouldIgnore: typeof _utils_shouldIgnore,
    },
};

export default _default;
