import buildFileDataList from './buildFileDataList.js';
import buildExportsTree from './buildExportsTree.js';
import generateImportStatements from './generateImportStatements.js';
import generateFlatExportLines from './generateFlatExportLines.js';
import generateNamespaceExportLines from './generateNamespaceExportLines.js';
import generateNamedExports from './generateNamedExports.js';

export default function generateFile(src, exportRoots, ignore, includeComments, dts, useTabs = true) {

	const fileDataList = buildFileDataList(src, ignore, includeComments);
	const {
		flatExports, nestedExports 
	} = buildExportsTree(fileDataList);
	const headerComment = `/**
 * This file is auto-generated by the build script.
 * It consolidates API ${dts ? 'type declarations' : 'functions'} for use in the application.
 * Do not edit manually.
 */
`;
	const importStatements = generateImportStatements(fileDataList, dts, src);
	const flatExportLines = generateFlatExportLines(flatExports, exportRoots, includeComments, dts, useTabs);
	const namespaceExportLines = generateNamespaceExportLines(nestedExports, includeComments, dts, useTabs);
	
	const defaultExportCode = dts
		? `declare const _default: {\n${flatExportLines}${namespaceExportLines}};\n\nexport default _default;\n`
		: `export default {\n${flatExportLines}${namespaceExportLines}};`;

	const namedExports = generateNamedExports(flatExports, exportRoots, dts);

    
	return headerComment +
           importStatements + '\n' +
           namedExports + '\n' +
           defaultExportCode;

}